#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "🔍 Running pre-commit checks..."

# Run lint-staged
npx lint-staged --edit $1

# Check if there are any linting errors
if [ $? -ne 0 ]; then
  echo "❌ Pre-commit checks failed!"
  exit 1
fi

echo "✅ Pre-commit checks passed!"